### ISSUE TITLE
config.sh otoro doesn't always find kineto_gan.ko

### ISSUE THREAD

**Issue by dhylands** [mozilla-b2g/android-device-otoro#1]
I just got my new otoro, and when I run:

./config.sh otoro

I get the following error:

...
Pulling "ar6000.ko"
1479 KB/s (598684 bytes in 0.395s)
Pulling "kineto_gan.ko"
remote object '/system/wifi/kineto_gan.ko' does not exist
Failed to pull kineto_gan.ko. Giving up.
Configuration failed

The /system/wifi on my phone only contains the ar6000.ko file

**Comment by dhylands** [comment]
I was able to resolve this by extracting the kineto_gan.ko file from the kernel update. I couldn't flash the kernel update since I didn't have fastboot. fastboot is built by calling buiid.sh, which needs ./config.sh, which needs kineto_gan.ko

**Comment by michaelwu** [comment]
Shouldn't be an issue on standard ICS flashed phones.
